### Data ingestion

In [2]:
import xml.etree.ElementTree as ET
import pandas as pd


tree = ET.parse('Dataset/customers.xml')

root = tree.getroot()

list_customers = []

for customer in root.findall('customer'):
   data = {
      'customer_id':  customer.find('customer_id').text, 
      'first_name': customer.find('first_name').text, 
      'last_name': customer.find('last_name').text, 
      'email': customer.find('email').text,
      'city': customer.find('city').text
   }

   list_customers.append(data)
df_customer  = pd.DataFrame(list_customers)
df_customer.head()

  customer_id first_name last_name                    email        city
0           1      Ahmed       Ali          ahmed@gmail.com       Cairo
1           2    Mohamed    Hassan        mohamed@gmail.com        Giza
2           3       Omar   Mahmoud           omar@gmail.com  Alexandria
3           4       Sara   Ibrahim   sara.ibrahim@gmail.com       Luxor
4           5    Youssef     Nabil  youssef.nabil@yahoo.com       Aswan

In [3]:
import xml.etree.ElementTree as ET
import pandas as pd


tree = ET.parse('Dataset/products.xml')

root = tree.getroot()

list_products = []

for product in root.findall('product'):
   data = {
      'product_id':  product.find('product_id').text, 
      'product_name': product.find('product_name').text, 
      'category': product.find('category').text, 
      'brand': product.find('brand').text,
      'price': product.find('price').text
   }

   list_products.append(data)
df_products  = pd.DataFrame(list_products)
df_products.head()

  product_id    product_name     category     brand   price
0        101       iPhone 15  Electronics     Apple  799.99
1        102      Galaxy S24  Electronics   Samsung  699.99
2        103    Nike Air Max        Shoes      Nike  129.99
3        104       Air Fryer         Home   Philips  149.99
4        105  Wireless Mouse  Electronics  Logitech   25.50

In [4]:
import xml.etree.ElementTree as ET
import pandas as pd


tree = ET.parse('Dataset/orders.xml')

root = tree.getroot()

list_orders = []

for order in root.findall('order'):
   data = {
      'order_id':  order.find('order_id').text, 
      'customer_id': order.find('customer_id').text, 
      'product_id': order.find('product_id').text, 
      'quantity': order.find('quantity').text,
      'order_date': order.find('order_date').text
   }

   list_orders.append(data)
df_orders  = pd.DataFrame(list_orders)
df_orders.head()

  order_id customer_id product_id quantity  order_date
0     1001           1        101        1  2026-09-01
1     1002           2        102        2  2026-09-02
2     1003           1        103        1  2026-09-03
3     1004           3        104        3  2026-09-04
4     1005           4        105        2  2026-09-05

### Bronze layer

In [5]:
!pip install pyodbc
import pyodbc

conn = pyodbc.connect(
    "driver={ODBC Driver 17 for SQL Server};"
    "Server=localhost;"
    "Database=Sales_DWH;"
    "Trusted_Connection=yes;"
)

cursor = conn.cursor()

Requirement already satisfied: pyodbc in C:\Users\HUAWEI\AppData\Local\Programs\Python\Python314\Lib\site-packages (5.3.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
df_customer.columns

Index(['customer_id', 'first_name', 'last_name', 'email', 'city'], dtype='str')

In [7]:
df_customer_result = list(df_customer.itertuples(index=None, name=None))
df_customer_result

[('1', 'Ahmed', 'Ali', 'ahmed@gmail.com', 'Cairo'),
 ('2', 'Mohamed', 'Hassan', 'mohamed@gmail.com', 'Giza'),
 ('3', 'Omar', 'Mahmoud', 'omar@gmail.com', 'Alexandria'),
 ('4', 'Sara', 'Ibrahim', 'sara.ibrahim@gmail.com', 'Luxor'),
 ('5', 'Youssef', 'Nabil', 'youssef.nabil@yahoo.com', 'Aswan'),
 ('6', 'Mona', 'Adel', 'mona.adel@gmail.com', 'Mansoura'),
 ('7', 'Khaled', 'Samir', 'khaled.samir@outlook.com', 'Tanta'),
 ('8', 'Nour', 'Elsayed', 'nour.elsayed@gmail.com', 'Suez'),
 ('9', 'Hana', 'Yasser', 'hana.yasser@gmail.com', 'Ismailia'),
 ('10', 'Karim', 'Fouad', 'karim.fouad@gmail.com', 'Cairo'),
 ('11', 'Laila', 'Kamal', 'laila.kamal@yahoo.com', 'Port Said'),
 ('12', 'Mostafa', 'Rashad', 'mostafa.rashad@gmail.com', 'Fayoum'),
 ('13', 'Dina', 'Hatem', 'dina.hatem@gmail.com', 'Zagazig'),
 ('14', 'Amr', 'Zaki', 'amr.zaki@hotmail.com', 'Minya'),
 ('15', 'Rana', 'Fathy', 'rana.fathy@gmail.com', 'Qena'),
 ('16', 'Tarek', 'Saleh', 'tarek.saleh@gmail.com', 'Sohag'),
 ('17', 'Mariam', 'Ashraf', 'mariam.ashraf@gmail.com', 'Beni Suef'),
 ('18', 'Hassan', 'Gamal', 'hassan.gamal@yahoo.com', 'Damietta'),
 ('19', 'Salma', 'Wael', 'salma.wael@gmail.com', 'Giza'),
 ('20', 'Bassel', 'Sherif', 'bassel.sherif@outlook.com', 'Cairo'),
 ('21', 'Farida', 'Kamal', 'farida.kamal@gmail.com', 'Alexandria'),
 ('22', 'Mahmoud', 'Ezzat', 'mahmoud.ezzat@yahoo.com', 'Luxor'),
 ('23', 'Reem', 'Hosny', 'reem.hosny@gmail.com', 'Aswan'),
 ('24', 'Ziad', 'Fouad', 'ziad.fouad@hotmail.com', 'Mansoura'),
 ('25', 'Nada', 'Adel', 'nada.adel@gmail.com', 'Tanta'),
 ('26', 'Sherif', 'Nabil', 'sherif.nabil@outlook.com', 'Suez'),
 ('27', 'Yara', 'Samir', 'yara.samir@gmail.com', 'Ismailia'),
 ('28', 'Ali', 'Mostafa', 'ali.mostafa@yahoo.com', 'Port Said'),
 ('29', 'Heba', 'Rashad', 'heba.rashad@gmail.com', 'Fayoum'),
 ('30', 'Kareem', 'Hatem', 'kareem.hatem@gmail.com', 'Zagazig'),
 ('31', 'Ghada', 'Zaki', 'ghada.zaki@hotmail.com', 'Minya'),
 ('32', 'Adel', 'Fathy', 'adel.fathy@gmail.com', 'Qena'),
 ('33', 'Menna', 'Saleh', 'menna.saleh@gmail.com', 'Sohag'),
 ('34', 'Ramy', 'Ashraf', 'ramy.ashraf@yahoo.com', 'Beni Suef'),
 ('35', 'Esraa', 'Gamal', 'esraa.gamal@gmail.com', 'Damietta'),
 ('36', 'Walid', 'Wael', 'walid.wael@outlook.com', 'Giza'),
 ('37', 'Rania', 'Sherif', 'rania.sherif@gmail.com', 'Cairo'),
 ('38', 'Tamer', 'Kamal', 'tamer.kamal@yahoo.com', 'Alexandria'),
 ('39', 'Doaa', 'Ezzat', 'doaa.ezzat@gmail.com', 'Luxor'),
 ('40', 'Ehab', 'Hosny', 'ehab.hosny@hotmail.com', 'Aswan'),
 ('41', 'Shaimaa', 'Fouad', 'shaimaa.fouad@gmail.com', 'Mansoura'),
 ('42', 'Hazem', 'Adel', 'hazem.adel@outlook.com', 'Tanta'),
 ('43', 'Nourhan', 'Nabil', 'nourhan.nabil@gmail.com', 'Suez'),
 ('44', 'Islam', 'Samir', 'islam.samir@yahoo.com', 'Ismailia'),
 ('45', 'Aya', 'Mostafa', 'aya.mostafa@gmail.com', 'Port Said'),
 ('46', 'Basma', 'Rashad', 'basma.rashad@gmail.com', 'Fayoum'),
 ('47', 'Maged', 'Hatem', 'maged.hatem@hotmail.com', 'Zagazig'),
 ('48', 'Passant', 'Zaki', 'passant.zaki@gmail.com', 'Minya'),
 ('49', 'Fady', 'Fathy', 'fady.fathy@yahoo.com', 'Qena'),
 ('50', 'Habiba', 'Saleh', 'habiba.saleh@gmail.com', 'Sohag')]

In [8]:
cursor.executemany("insert into bronze1.Customers values (? , ? , ? , ? , ?)", df_customer_result)
conn.commit()

In [9]:
df_products.columns

Index(['product_id', 'product_name', 'category', 'brand', 'price'], dtype='str')

In [10]:
df_products_result = list(df_products.itertuples(index=None, name=None))
df_products_result

[('101', 'iPhone 15', 'Electronics', 'Apple', '799.99'),
 ('102', 'Galaxy S24', 'Electronics', 'Samsung', '699.99'),
 ('103', 'Nike Air Max', 'Shoes', 'Nike', '129.99'),
 ('104', 'Air Fryer', 'Home', 'Philips', '149.99'),
 ('105', 'Wireless Mouse', 'Electronics', 'Logitech', '25.50'),
 ('106', 'Office Chair', 'Furniture', 'IKEA', '199.00'),
 ('107', 'Running Shorts', 'Clothing', 'Adidas', '19.99'),
 ('108', 'Coffee Maker', 'Home', 'Nespresso', '129.00'),
 ('109', 'Leather Wallet', 'Accessories', 'Gucci', '199.00'),
 ('110', 'Bluetooth Speaker', 'Electronics', 'JBL', '89.99')]

In [11]:
cursor.executemany("insert into bronze1.Products values (? , ? , ? , ? , ?)", df_products_result)
conn.commit()

In [12]:
df_orders.columns

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'order_date'], dtype='str')

In [13]:
df_orders_result = list(df_orders.itertuples(index=None, name=None))
df_orders_result

[('1001', '1', '101', '1', '2026-09-01'),
 ('1002', '2', '102', '2', '2026-09-02'),
 ('1003', '1', '103', '1', '2026-09-03'),
 ('1004', '3', '104', '3', '2026-09-04'),
 ('1005', '4', '105', '2', '2026-09-05'),
 ('1006', '5', '106', '1', '2026-09-06'),
 ('1007', '6', '107', '4', '2026-09-07'),
 ('1008', '7', '108', '1', '2026-09-08'),
 ('1009', '8', '109', '2', '2026-09-09'),
 ('1010', '9', '110', '3', '2026-09-10'),
 ('1011', '10', '101', '1', '2026-09-11'),
 ('1012', '11', '102', '2', '2026-09-12'),
 ('1013', '12', '103', '5', '2026-09-13'),
 ('1014', '13', '104', '1', '2026-09-14'),
 ('1015', '14', '105', '2', '2026-09-15'),
 ('1016', '15', '106', '1', '2026-09-16'),
 ('1017', '16', '107', '3', '2026-09-17'),
 ('1018', '17', '108', '2', '2026-09-18'),
 ('1019', '18', '109', '1', '2026-09-19'),
 ('1020', '19', '110', '4', '2026-09-20'),
 ('1021', '20', '101', '2', '2026-09-21'),
 ('1022', '21', '102', '1', '2026-09-22'),
 ('1023', '22', '103', '3', '2026-09-23'),
 ('1024', '23', '104', '1', '2026-09-24'),
 ('1025', '24', '105', '2', '2026-09-25'),
 ('1026', '25', '106', '1', '2026-09-26'),
 ('1027', '26', '107', '5', '2026-09-27'),
 ('1028', '27', '108', '2', '2026-09-28'),
 ('1029', '28', '109', '1', '2026-09-29'),
 ('1030', '29', '110', '3', '2026-09-30')]

In [14]:
cursor.executemany("insert into bronze1.Orders values (? , ? , ? , ? , ?)", df_orders_result)
conn.commit()

In [15]:
conn.close()

### Silver layer

In [16]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://localhost/Sales_dwh"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
    "&TrustServerCertificate=yes"
)

In [17]:
df_customers =pd.read_sql("select * from bronze1.Customers",engine)
df_products =pd.read_sql("select * from bronze1.Products",engine)
df_orders =pd.read_sql("select * from bronze1.Orders",engine)

In [18]:
df_customers.dtypes

customer_id    str
firstname      str
lastname       str
email          str
city           str
dtype: object

In [19]:
df_customers['customer_id']  = df_customers['customer_id'].astype(int)

In [20]:
df_customers.dtypes

customer_id    int64
firstname        str
lastname         str
email            str
city             str
dtype: object

In [21]:
df_customers['full_name']  = df_customers['firstname'] + ' ' + df_customers['lastname']

In [22]:
df_customers.drop(columns=['firstname', 'lastname'], inplace=True)

In [23]:
df_products.head()

  product_id    product_name     category     brand   price
0        101       iPhone 15  Electronics     Apple  799.99
1        102      Galaxy S24  Electronics   Samsung  699.99
2        103    Nike Air Max        Shoes      Nike  129.99
3        104       Air Fryer         Home   Philips  149.99
4        105  Wireless Mouse  Electronics  Logitech   25.50

In [24]:
df_products['product_id']  = df_products['product_id'].astype(int)
df_products['price']  = df_products['price'].astype(float)

In [25]:
df_products.dtypes

product_id        int64
product_name        str
category            str
brand               str
price           float64
dtype: object

In [26]:
df_orders.head()

  Order_id customer_id product_id quantity  order_date
0     1001           1        101        1  2026-09-01
1     1002           2        102        2  2026-09-02
2     1003           1        103        1  2026-09-03
3     1004           3        104        3  2026-09-04
4     1005           4        105        2  2026-09-05

In [27]:
df_orders.dtypes

Order_id       str
customer_id    str
product_id     str
quantity       str
order_date     str
dtype: object

In [28]:
df_orders['Order_id']  = df_orders['Order_id'].astype(int)
df_orders['customer_id'] = df_orders['customer_id'].astype('Int64')
df_orders['product_id']  = df_orders['product_id'].astype(int)
df_orders['quantity']  = df_orders['quantity'].astype(int)  
df_orders['order_date'] = pd.to_datetime(df_orders['order_date'], format='%Y-%m-%d')

In [33]:
df_customers
df_products
df_orders

    Order_id  customer_id  product_id  quantity order_date
0       1001            1         101         1 2026-09-01
1       1002            2         102         2 2026-09-02
2       1003            1         103         1 2026-09-03
3       1004            3         104         3 2026-09-04
4       1005            4         105         2 2026-09-05
5       1006            5         106         1 2026-09-06
6       1007            6         107         4 2026-09-07
7       1008            7         108         1 2026-09-08
8       1009            8         109         2 2026-09-09
9       1010            9         110         3 2026-09-10
10      1011           10         101         1 2026-09-11
11      1012           11         102         2 2026-09-12
12      1013           12         103         5 2026-09-13
13      1014           13         104         1 2026-09-14
14      1015           14         105         2 2026-09-15
15      1016           15         106         1 2026-09-16
16      1017           16         107         3 2026-09-17
17      1018           17         108         2 2026-09-18
18      1019           18         109         1 2026-09-19
19      1020           19         110         4 2026-09-20
20      1021           20         101         2 2026-09-21
21      1022           21         102         1 2026-09-22
22      1023           22         103         3 2026-09-23
23      1024           23         104         1 2026-09-24
24      1025           24         105         2 2026-09-25
25      1026           25         106         1 2026-09-26
26      1027           26         107         5 2026-09-27
27      1028           27         108         2 2026-09-28
28      1029           28         109         1 2026-09-29
29      1030           29         110         3 2026-09-30

In [34]:
df_customers.to_sql(
    'customers',
    con = engine,
    schema = 'silver',
    if_exists = 'append',
    index = False
)

100

In [35]:
df_products.to_sql(
    'products',
    con = engine,
    schema = 'silver',
    if_exists = 'append',
    index = False
)

20

In [37]:
df_orders.to_sql(
    'orders',
    con = engine,
    schema = 'silver',
    if_exists = 'append',
    index = False
)

30

### Gold layer

In [38]:
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://localhost/Sales_dwh"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
    "&TrustServerCertificate=yes"
)

In [39]:
df_custmers = pd.read_sql("select * from silver.customers", engine)
df_products = pd.read_sql("select * from silver.products", engine)
df_orders = pd.read_sql("select * from silver.orders", engine)

In [40]:
df_output = pd.merge(df_orders, df_custmers, how='inner', on='customer_id')

In [41]:
df_output

,Order_id,customer_id,product_id,quantity,order_date,full_name,email,city
0,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo
1,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo
2,1002,2,102,2,2026-09-02,Mohamed Hassan,mohamed@gmail.com,Giza
3,1002,2,102,2,2026-09-02,Mohamed Hassan,mohamed@gmail.com,Giza
4,1003,1,103,1,2026-09-03,Ahmed Ali,ahmed@gmail.com,Cairo
5,1003,1,103,1,2026-09-03,Ahmed Ali,ahmed@gmail.com,Cairo
6,1004,3,104,3,2026-09-04,Omar Mahmoud,omar@gmail.com,Alexandria
7,1004,3,104,3,2026-09-04,Omar Mahmoud,omar@gmail.com,Alexandria
8,1005,4,105,2,2026-09-05,Sara Ibrahim,sara.ibrahim@gmail.com,Luxor
9,1005,4,105,2,2026-09-05,Sara Ibrahim,sara.ibrahim@gmail.com,Luxor
10,1006,5,106,1,2026-09-06,Youssef Nabil,youssef.nabil@yahoo.com,Aswan
11,1006,5,106,1,2026-09-06,Youssef Nabil,youssef.nabil@yahoo.com,Aswan
12,1007,6,107,4,2026-09-07,Mona Adel,mona.adel@gmail.com,Mansoura
13,1007,6,107,4,2026-09-07,Mona Adel,mona.adel@gmail.com,Mansoura
14,1008,7,108,1,2026-09-08,Khaled Samir,khaled.samir@outlook.com,Tanta
15,1008,7,108,1,2026-09-08,Khaled Samir,khaled.samir@outlook.com,Tanta
16,1009,8,109,2,2026-09-09,Nour Elsayed,nour.elsayed@gmail.com,Suez
17,1009,8,109,2,2026-09-09,Nour Elsayed,nour.elsayed@gmail.com,Suez
18,1010,9,110,3,2026-09-10,Hana Yasser,hana.yasser@gmail.com,Ismailia
19,1010,9,110,3,2026-09-10,Hana Yasser,hana.yasser@gmail.com,Ismailia
20,1011,10,101,1,2026-09-11,Karim Fouad,karim.fouad@gmail.com,Cairo
21,1011,10,101,1,2026-09-11,Karim Fouad,karim.fouad@gmail.com,Cairo
22,1012,11,102,2,2026-09-12,Laila Kamal,laila.kamal@yahoo.com,Port Said
23,1012,11,102,2,2026-09-12,Laila Kamal,laila.kamal@yahoo.com,Port Said
24,1013,12,103,5,2026-09-13,Mostafa Rashad,mostafa.rashad@gmail.com,Fayoum
25,1013,12,103,5,2026-09-13,Mostafa Rashad,mostafa.rashad@gmail.com,Fayoum
26,1014,13,104,1,2026-09-14,Dina Hatem,dina.hatem@gmail.com,Zagazig
27,1014,13,104,1,2026-09-14,Dina Hatem,dina.hatem@gmail.com,Zagazig
28,1015,14,105,2,2026-09-15,Amr Zaki,amr.zaki@hotmail.com,Minya
29,1015,14,105,2,2026-09-15,Amr Zaki,amr.zaki@hotmail.com,Minya
30,1016,15,106,1,2026-09-16,Rana Fathy,rana.fathy@gmail.com,Qena
31,1016,15,106,1,2026-09-16,Rana Fathy,rana.fathy@gmail.com,Qena
32,1017,16,107,3,2026-09-17,Tarek Saleh,tarek.saleh@gmail.com,Sohag
33,1017,16,107,3,2026-09-17,Tarek Saleh,tarek.saleh@gmail.com,Sohag
34,1018,17,108,2,2026-09-18,Mariam Ashraf,mariam.ashraf@gmail.com,Beni Suef
35,1018,17,108,2,2026-09-18,Mariam Ashraf,mariam.ashraf@gmail.com,Beni Suef
36,1019,18,109,1,2026-09-19,Hassan Gamal,hassan.gamal@yahoo.com,Damietta
37,1019,18,109,1,2026-09-19,Hassan Gamal,hassan.gamal@yahoo.com,Damietta
38,1020,19,110,4,2026-09-20,Salma Wael,salma.wael@gmail.com,Giza
39,1020,19,110,4,2026-09-20,Salma Wael,salma.wael@gmail.com,Giza
40,1021,20,101,2,2026-09-21,Bassel Sherif,bassel.sherif@outlook.com,Cairo
41,1021,20,101,2,2026-09-21,Bassel Sherif,bassel.sherif@outlook.com,Cairo
42,1022,21,102,1,2026-09-22,Farida Kamal,farida.kamal@gmail.com,Alexandria
43,1022,21,102,1,2026-09-22,Farida Kamal,farida.kamal@gmail.com,Alexandria
44,1023,22,103,3,2026-09-23,Mahmoud Ezzat,mahmoud.ezzat@yahoo.com,Luxor
45,1023,22,103,3,2026-09-23,Mahmoud Ezzat,mahmoud.ezzat@yahoo.com,Luxor
46,1024,23,104,1,2026-09-24,Reem Hosny,reem.hosny@gmail.com,Aswan
47,1024,23,104,1,2026-09-24,Reem Hosny,reem.hosny@gmail.com,Aswan
48,1025,24,105,2,2026-09-25,Ziad Fouad,ziad.fouad@hotmail.com,Mansoura
49,1025,24,105,2,2026-09-25,Ziad Fouad,ziad.fouad@hotmail.com,Mansoura
50,1026,25,106,1,2026-09-26,Nada Adel,nada.adel@gmail.com,Tanta
51,1026,25,106,1,2026-09-26,Nada Adel,nada.adel@gmail.com,Tanta
52,1027,26,107,5,2026-09-27,Sherif Nabil,sherif.nabil@outlook.com,Suez
53,1027,26,107,5,2026-09-27,Sherif Nabil,sherif.nabil@outlook.com,Suez
54,1028,27,108,2,2026-09-28,Yara Samir,yara.samir@gmail.com,Ismailia
55,1028,27,108,2,2026-09-28,Yara Samir,yara.samir@gmail.com,Ismailia
56,1029,28,109,1,2026-09-29,Ali Mostafa,ali.mostafa@yahoo.com,Port Said
57,1029,28,109,1,2026-09-29,Ali Mostafa,ali.mostafa@yahoo.com,Port Said
58,1030,29,110,3,2026-09-30,Heba Rashad,heba.rashad@gmail.com,Fayoum
59,1030,29,110,3,2026-09-30,Heba Rashad,heba.rashad@gmail.com,Fayoum

In [42]:
df_output = pd.merge(df_output, df_products, how='inner', on='product_id')

In [44]:
df_output.head()

,Order_id,customer_id,product_id,quantity,order_date,full_name,email,city,product_name,category,brand,price
0,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo,iPhone 15,Electronics,Apple,799.99
1,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo,iPhone 15,Electronics,Apple,799.99
2,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo,iPhone 15,Electronics,Apple,799.99
3,1001,1,101,1,2026-09-01,Ahmed Ali,ahmed@gmail.com,Cairo,iPhone 15,Electronics,Apple,799.99
4,1002,2,102,2,2026-09-02,Mohamed Hassan,mohamed@gmail.com,Giza,Galaxy S24,Electronics,Samsung,699.99

In [45]:
df_output['total_amount'] = df_output['quantity'] * df_output['price']

In [46]:
df_output.dtypes

Order_id          int64
customer_id       int64
product_id        int64
quantity          int64
order_date       object
full_name           str
email               str
city                str
product_name        str
category            str
brand               str
price           float64
total_amount    float64
dtype: object

In [47]:
df_output.to_sql(
    'main',
    con = engine,
    schema = 'gold',
    if_exists = 'append',
    index = False
)

120